#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Quit,
    FocusProcessList,
    FocusTerminal,
    ToggleZoom,
    SelectNext,
    SelectPrev,
    StartProcess,
    StopProcess,
    RestartProcess,
    ForceKill,
    ClearLogs,
    ToggleKeymap,
    ScrollUp(u16),
    ScrollDown(u16),
    SwitchToPortKiller,
    SwitchToProcesses,
    PortKillerType(char),
    PortKillerBackspace,
    PortKillerClear,
    SelectIndex(usize),
    ClickOutputPane,
    MouseDragStart(u16, u16),
    MouseDragEnd(u16, u16),
    CopySelection,
    SendInput(Vec<u8>),
    Resize(u16, u16),
    None,
}
